import { Link } from "react-router-dom";
import { Helmet } from "react-helmet-async";

function LandingPage() {
  return (
    <section className="flex flex-col w-3/4 max-md:w-full items-center justify-between py-10 px-6 min-h-full">
      <Helmet>
        <title>{`iChatAI: an AI-human chat app.`}</title>
        <meta
          name="description"
          content={`iChatAI app is an AI chat app that generates response to your question.`}
        />
      </Helmet>
      <div className="w-full flex items-center flex-col gap-4">
        <h2 className="text-3xl font-bold">iChatAI</h2>
        <p className="text-center w-[27rem] max-sm:w-[88%] text-base">
          Responses are generated by AI. You ask, you get response. So yes, you
          can say <span className="italic">&quot;I Chat AI&quot;</span>.
        </p>
      </div>
      <img src="../chat-ai.svg" alt="ai illustration" />
      <Link
        to="/chats"
        className="w-max h-max text-white rounded-[3rem] bg-human flex gap-4 items-center px-4 py-2 border-none outline-none hover:outline-clr1 focus:outline-clr1 focus:border-white transition-all text-base"
      >
        Continue &#8594;
      </Link>
    </section>
  );
}

export default LandingPage;
