function LandingPage() {
  return (
    <section className="flex flex-col w-3/4 min-h-svh justify-between items-center py-14 px-4 bg-primary">
      <div className="w-full flex items-center flex-col gap-4">
        <h2 className="text-3xl font-bold">iChatAI</h2>
        <p>
          Responses are generated by AI. You ask, you get answer. So yes, you
          can say &quot;iChatAI&quot;.
        </p>
      </div>
      <img src="../chat-ai.svg" alt="ai illustration" />
      <a href="#">Continue &#8594;</a>
    </section>
  );
}

export default LandingPage;
